name: Asher
favicon: null
layout_spectrum: 0.27651263447478414
typography_spectrum: 0.37232162104919553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12910460820421576
  lightness: 0.023337666410952806
  saturation: 0.9394748525228351
  rhythmicContrast: 0.4652365215588361
purpose: []
